export const chatRoomList = [
  {
    id: 1,
    name: 'room name1',
    coverImg: '',
    lastMessage: 'hello world',
    private: true,
  },
  {
    id: 2,
    name: 'room name2',
    coverImg: '',
    lastMessage: 'Hello world2asadasdasdasdasdasdasdasdasdasdasdadasdasdasda',
    private: false,
    members: [1, 3, 4],
  },
  {
    id: 3,
    name: 'room name3',
    coverImg: '../images/github_logo.png',
    lastMessage: 'hello world',
    private: false,
    members: [1, 3, 5, 7, 8, 9],
  },
  {
    id: 4,
    name: 'room name4',
    coverImg: '',
    lastMessage: 'Hello world4',
    private: false,
    members: [1, 3, 5, 6, 8, 9, 11],
  },
  {
    id: 5,
    name: 'room name4',
    coverImg: '../images/github_logo.png',
    lastMessage: 'Hello world4',
    private: true,
  },
  {
    id: 6,
    name: 'room name4',
    coverImg: '../images/github_logo.png',
    lastMessage: 'Hello world4',
    private: false,
    members: [1, 3, 5, 7],
  },
  {
    id: 7,
    name: 'room name4',
    coverImg: '../images/github_logo.png',
    lastMessage: 'Hello world4',
    private: false,
    members: [1, 3, 5, 7],
  },
  {
    id: 8,
    name: 'room name4',
    coverImg: '../images/github_logo.png',
    lastMessage: 'Hello world4',
    private: false,
    members: [1, 3, 5, 7],
  },
  {
    id: 9,
    name: 'room name4',
    coverImg: '../images/github_logo.png',
    lastMessage: 'Hello world4',
    private: true,
  },
  {
    id: 10,
    name: 'room name4',
    coverImg: '../images/github_logo.png',
    lastMessage: 'Hello world4',
    private: true,
  },
  {
    id: 11,
    name: 'room name4',
    coverImg: '../images/github_logo.png',
    lastMessage: 'Hello world4',
    private: true,
  },
  {
    id: 12,
    name: 'room name4',
    coverImg: '../images/github_logo.png',
    lastMessage: 'Hello world4',
    private: false,
    members: [1, 3, 5, 7],
  },
  {
    id: 13,
    name: 'room name4',
    coverImg: '../images/github_logo.png',
    lastMessage: 'Hello world4',
    private: false,
    members: [1, 3, 5, 7],
  },
];
